# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        

    - name: Setup Maven
  # You may pin to the exact commit or the version.
  # uses: stCarolas/setup-maven@3c9ddfb1c6df927e174580018dd71e774bc7dd48
      uses: stCarolas/setup-maven@v4.1
      with:
    # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
       maven-version: 3.5.4
    
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: mvn install
      run: mvn install
    
        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        - run: npm install
        - run: npm i -g snyk
        - run: snyk auth ${{ secrets.SNYK_TOKEN }}
        - run: snyk monitor
      #  - run: npm ci
     #   - run: npm run build --if-present
      #  - run: npm test

        - run: npm install snyk-to-html -g
        - run: npm install snyk
        - run: snyk test --json | snyk-to-html -o result.html
#

